int check(int x, int y, int n);
int gcd(int m, int n);
int day_of_year(int month, int day, int year);
int num_digits(int n);
int digit(int n, int k);
int evaluate_position(char board[8][8]);
double median(double x, double y, double z);
int fact(int n);
int fact_no_recursion(int n);
int gcd_recursive(int a, int b);
void pb(int n);
